### ISSUE TITLE
Add overclock feature to S9k

### ISSUE THREAD

**Issue by jamnaga** [minershive/hiveos-asic#21]
Hello, I was seeing that on commit [b52e0f440137b795a8fe994f5fcbb87fa0169748](https://github.com/minershive/hiveos-asic/commit/b52e0f440137b795a8fe994f5fcbb87fa0169748) you wrote that this feature would be added 'soon' but from the 2 last year, nothing changed.

Any news about?

**Comment by j2h4u** [comment]
Hello,

It's great you've mentioned this, thanks for the question! I suppose I owe you some explanation. Two years ago we had S9k Hiveon Firmware in our agenda, but it's been years... And that agenda had evolved in mysterious ways. We still don't have ETA for S9k Hiveon Firmware. Please stay tuned

**Comment by jamnaga** [comment]
Hello, thank @j2h4u for the fast reply.

There is a way to downclock it instead? I need the capability to reduce its power draw.

**Comment by j2h4u** [comment]
You're welcome.

We don't have the Hiveon firmware for this model at the moment. It might be that some third-party firmware out there has a downclock feature--please do your own research.

Just to be clear, this very repository is labeled "Hiveon ASIC Client", rather than "Hiveon Firmware". Our business here is to develop firmware-independent Plumbing and Porcelain, at most. You know, a plain old "gather a telemetry data/parse it/send to backend" scheme, that's all
